apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: osrm-project
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: routing-front-bc
      labels:
        app: routing-front
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: routing-front
        app.kubernetes.io/name: routing-front
        app.kubernetes.io/part-of: osrm-project
    spec:
      source:
        type: Git
        git:
          uri: https://github.com/HY-OHTUPROJ-OSRM/routing-front
          ref: master
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          buildArgs:
            - name: ROUTING_API_URL
              value: "https://routing-api-ohtuprojekti-staging.apps.ocp-prod-0.k8s.it.helsinki.fi/"
      resources:
        limits:
          memory: "8Gi"
          cpu: "500m"
        requests:
          memory: "2Gi"
          cpu: "500m"
      output:
        to:
          kind: ImageStreamTag
          name: routing-front-is:latest
      triggers:
        - type: ConfigChange
        - type: ImageChange
      resources: {}
