apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - routing-front/imagestream.yaml
  - routing-front/deployment.yaml
  - routing-front/service.yaml
  - routing-front/route.yaml
