apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: osrm-project
objects:
  - apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization

    resources:
      - secret.yaml
      - configmap.yaml
