apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: osrm-project
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: routing-db-secret
      labels:
        app: routing-db
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: routing-db
        app.kubernetes.io/name: routing-db
        app.kubernetes.io/part-of: osrm-project
        app.openshift.io/runtime: postgresql
    type: Opaque
    stringData:
      password: ${POSTGRES_PASSWORD}

parameters:
- name: POSTGRES_PASSWORD
