apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: osrm-project
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: routing-db-secret
    type: Opaque
    stringData:
      password: ${POSTGRES_PASSWORD}

parameters:
- name: POSTGRES_PASSWORD
