volumes: 
  osrm_db:

services:
  osrm-db:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - osrm_db:/var/lib/postgresql/data

  osrm-backend:
    build:
      context: https://github.com/Project-OSRM/osrm-backend.git#f5e92418991f86c3a18bbc85df71868a1d378e01 # hardcoded lol
      dockerfile: docker/Dockerfile-debian
      tags:
        - osrm-backend:v6.0.0-debian

  routing-api:
    build:
      context: https://github.com/HY-OHTUPROJ-OSRM/routing-api.git
      additional_contexts:
        base: service:osrm-backend
      tags:
        - routing-api
    environment:
      - BACKEND_URL=http://0.0.0.0:5000
      - OSRM_BACKEND_PORT=5000
      - DATABASE_HOST=osrm-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=pass
    ports:
      - 3000:3000
    depends_on:
      - osrm-db
    
  routing-front:
    build: 
      context: https://github.com/HY-OHTUPROJ-OSRM/routing-front.git
      args:
        ROUTING_API_URL: http://localhost:3000
      tags:
        - routing-front
    ports:
      - 8080:8080
    depends_on:
      - routing-api
