volumes: 
  osrm_db:

services:
  osrm-db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - 5434:5432
    volumes:
      - osrm_db:/var/lib/postgresql/data

  osrm-backend:
    build:
      context: git@github.com:Project-OSRM/osrm-backend#f5e92418991f86c3a18bbc85df71868a1d378e01 # hardcoded lol
      dockerfile: docker/Dockerfile-debian
      tags:
        - osrm-backend:v6.0.0-debian

  routing-api:
    build:
      context: git@github.com:HY-OHTUPROJ-OSRM/routing-api.git
      additional_contexts:
        base: service:osrm-backend
      network: host
      tags:
        - routing-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BACKEND_URL=http://host.docker.internal:5001
      - OSRM_BACKEND_PORT=5001
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5434
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=pass
    ports:
      - 3000:3000
      - 5001:5001
    
  routing-front:
    build: 
      context: git@github.com:HY-OHTUPROJ-OSRM/routing-front.git
      args:
        ROUTING_API_URL: http://localhost:3000
      tags:
        - routing-front
    ports:
      - 8080:8080
    depends_on:
      - routing-api