apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: osrm-project
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: routing-api-dep
      labels:
        app: routing-api
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: routing-api
        app.kubernetes.io/name: routing-api
        app.kubernetes.io/part-of: osrm-project
        app.openshift.io/runtime: nodejs
      annotations:
        app.openshift.io/connects-to: map-database
        app.openshift.io/vcs-uri: https://github.com/HY-OHTUPROJ-OSRM/routing-api
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"routing-api-is:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"routing-api\")].image"}]'
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: routing-api
      template:
        metadata:
          labels:
            app: routing-api
        spec:
          containers:
          - name: routing-api
            image: routing-api-is:latest
            ports:
              - containerPort: 3000
            env:
              - name: BACKEND_URL
                value: http://0.0.0.0:5000
              - name: DATABASE_HOST
                value: possu.it.helsinki.fi
              - name: DATABASE_PORT
                value: "5432"
              - name: DATABASE_DB
                value: osrm_data
              - name: DATABASE_USER
                value: osrm_data
              - name: FORCE_SSL
                value: "true"
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: routing-db-secret
                    key: password
            resources:
              limits:
                memory: "3072Mi"
                cpu: "750m"
              requests:
                memory: "1024Mi"
                cpu: "250m"
