apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: osrm-project
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: routing-api-svc
      labels:
        app: routing-api
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: routing-api
        app.kubernetes.io/name: routing-api
        app.kubernetes.io/part-of: osrm-project
        app.openshift.io/runtime-version: latest
      annotations:
        app.openshift.io/connects-to: map-database
        app.openshift.io/vcs-uri: https://github.com/HY-OHTUPROJ-OSRM/routing-api
    spec:
      selector:
        app: routing-api
      ports:
        - name: 3000-tcp
          protocol: TCP
          port: 3000
          targetPort: 3000
